### ISSUE TITLE
Missing Characters in alpha-numeric default character sets

### ISSUE THREAD

**Issue by pbolduc** [exceptionless/Exceptionless.RandomData#1]
I noticed there appears to be some characters missing from random data character sets.  It is not obvious why these characters are missing other than by mistake.

[DEFAULT_ALPHA_CHARS](https://github.com/exceptionless/Exceptionless.RandomData/blob/master/Source/RandomData.cs#L196) is missing upper and lower 'i', lower 'l' (ell), upper and lower 'o'.

[DEFAULT_ALPHANUMERIC_CHARS](https://github.com/exceptionless/Exceptionless.RandomData/blob/master/Source/RandomData.cs#L201) is missing upper and lower 'i', lower 'l' (ell), upper and lower 'o', zero '0' and one '1'

**Comment by niemyjski** [comment]
Would you mind doing a pull request for this? The only reason I could think these would be missing is due to similar looking characters @ejsmith??

**Comment by ejsmith** [comment]
Yes, they are left out because they are hard to tell apart.

**Comment by niemyjski** [comment]
@pbolduc are you fine with these characters being left out? Do you think we should add a comment to the source code for this?

**Comment by pbolduc** [comment]
sure, a comment would be fine.

**Comment by niemyjski** [comment]
I've added a comment.

@ejsmith was there a reason https://github.com/exceptionless/Exceptionless.RandomData/blob/master/Source/RandomData.cs#L169 has all the characters while these two don't?
